name: eventlog-inferrence
channels:
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - pandas
  - conda-forge::dtaidistance
  - pip
  - pip:
    - ruptures
    - python-dateutil
    - influxdb
    - sklearn
    - stumpy
    - tslearn
    - dtaidistance
